version: '3'
services:
  directus:
    build:
      context: .
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    environment:
      PUBLIC_URL: $PUBLIC_URL
      KEY: $KEY
      SECRET: $SECRET
      ACCESS_TOKEN_TTL: $ACCESS_TOKEN_TTL
      REFRESH_TOKEN_TTL: $REFRESH_TOKEN_TTL
      DB_CLIENT: $DB_CLIENT
      DB_CONNECTION_STRING: $DB_CONNECTION_STRING
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      AUTH_PROVIDERS: $AUTH_PROVIDERS
      AUTH_GOOGLE_DRIVER: $AUTH_GOOGLE_DRIVER
      AUTH_GOOGLE_CLIENT_ID: $AUTH_GOOGLE_CLIENT_ID
      AUTH_GOOGLE_CLIENT_SECRET: $AUTH_GOOGLE_CLIENT_SECRET
      AUTH_GOOGLE_ISSUER_URL: $AUTH_GOOGLE_ISSUER_URL
      AUTH_GOOGLE_IDENTIFIER_KEY: $AUTH_GOOGLE_IDENTIFIER_KEY
      AUTH_GOOGLE_ICON: $AUTH_GOOGLE_ICON
      AUTH_GOOGLE_LABEL: $AUTH_GOOGLE_LABEL
      AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: $AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION
      AUTH_GOOGLE_DEFAULT_ROLE_ID: $AUTH_GOOGLE_DEFAULT_ROLE_ID
      STORAGE_LOCATIONS: $STORAGE_LOCATIONS
      STORAGE_S3_DRIVER: $STORAGE_S3_DRIVER
      STORAGE_S3_KEY: $STORAGE_S3_KEY
      STORAGE_S3_SECRET: $STORAGE_S3_SECRET
      STORAGE_S3_BUCKET: $STORAGE_S3_BUCKET
      STORAGE_S3_REGION: $STORAGE_S3_REGION
      STORAGE_S3_ENDPOINT: $STORAGE_S3_ENDPOINT